apiVersion: v1
kind: Service
metadata:
  name: documents-transfer
spec:
  selector:
    app: documents-transfer-deployment
    version: "${BUILD_ID}"
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
  type: NodePort